---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-ott-platform
  labels:
    app: prime-ott-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-ott-platform
  template:
    metadata:
      labels:
        app: prime-ott-platform
    spec:
      containers:
      - name: prime-ott-platform-container
        image: 859384797911.dkr.ecr.ap-southeast-1.amazonaws.com/prime-ott-platform:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
