---
apiVersion: v1
kind: Service
metadata:
  name: prime-ott-platform
  labels:
    app: prime-ott-platform
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: prime-ott-platform
  type: LoadBalancer

